### ISSUE TITLE
Pin fastcore versions

### ISSUE THREAD

**Issue by muellerzr** [Novetta/lib2nbdev#10]
Currently there is a config issue, and it's based on release 1.3.21 (Thanks Jeremy Howard for helping me narrow that down).

Next steps are to release two versions:
- 0.0.8, which pins the fastcore version used
- 0.0.9, which adds in the PR proposed in https://github.com/Novetta/lib2nbdev/pull/9 and also closes issue https://github.com/Novetta/lib2nbdev/issues/8

**Comment by manisnesan** [comment]
@muellerzr - I would love learn the process behind doing a release ( I can see it from Makefile there are two targets associated with it). If you could tag me when you start working on this issue, I would really appreciate it.
