### ISSUE TITLE
More helpful error messages when it comes to lib_path

### ISSUE THREAD

**Issue by muellerzr** [Novetta/lib2nbdev#3]
Received some feedback that `lib_path` should be better documented as stating "Where the library/py's are *currently* located" (or something similar)

**Comment by yegeniy** [comment]
I just ran into this. Hope the user experience below is helpful in some small way 🤞 :

I didn't receive a prompt to set my `lib_path`. I had to modify the `settings.ini` manually to set it, after the initial round of questions ended in an error.

After changing that, I guessed that I needed to run `convert_lib` again. 🎉 That worked! 

But it then ran into problems with setting up the GitHub Actions. 

```

> convert_lib

Checking for a settings.ini...
settings.ini already exists, please modify the existing version
Gathering files...
68 modules found in the library
Writing notebooks to /Users/ewolfson/dev/github.com/XXX/nbs...
XXX successfully converted!██████████████████████████████████████████████████████████████████| 100.00% [68/68 00:00<00:00]
Would you like to setup the automated Github workflow that nbdev provides? (0/1)1
main.yml already exists, please modify the existing version
Github actions generated! Please make sure to include .github/actions/main.yml in your next commit!

> la | grep git

drwxr-xr-x  15 ewolfson  staff   480B Jun 10 00:24 .git
-rw-r--r--   1 ewolfson  staff    83B Jun 10 00:11 .gitignore

```

There was a message that said "main.yml already exists, please modify the existing version". But there's no such file. 

Could one of these cases have tripped it up?
- There isn't a `.github` folder in this repository yet.
- There _is_ a file ending with `.yml` in the root directory.

**Comment by yegeniy** [comment]
Gotta say, this library is dope. Thank you @muellerzr 

I love that this much effort was put into something that's a "one-off". Converting the codebase might be a one-off task, but doing it by hand is a put-off. Without this library, I don't think I would've even considered it.
Now, minutes after starting,  I'm ready to bring down the power of literate programming on this convoluted codebase.  💥  

Any loose ends (like the one above) should end up being easy to fix. I can just adapt the GitHub actions and git hooks from another nbdev repo. The bulk of the work that this library does worked wonderfully and brilliantly quickly at that!

**Comment by muellerzr** [comment]
Very happy to hear you like the library so much Eugene!

Thinking on the two scenarios you mentioned, I believe what could be
happening here is it’s not sensing the .github folder, and then bugging
out. I will look into this soon!

Thank you for such a clear report!

**Comment by muellerzr** [comment]
@yegeniy this should be fixed now, if you so desire to please try it out!

**Comment by ew-meetup** [comment]
<details><summary>Thank you @muellerzr - it ran perfectly.</summary>

I didn't end up getting the code into a production scenario yet. Ended up running into problems with using this to develop Airflow DAGs. Airflow development isn't a great use-case for building a library, but I thought it'd be fine here.
Eventually, it didn't seem to be worth the effort of all the glue code it would take to get the DAGs into production using nbdev. 🤞 it's just inexperience with nbdev, but I suspect it's actually due to airflow's complex dependencies.

</details>
